# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: /
#url: http://www.jcohy.com
date_format: "ordinal"
title: Jcohy
subtitle: "越是错综复杂的问题。就越要根据简单的原理和朴素的思想进行判断和行动。"
description: "jcohy的个人博客"
keywords: jcohy, Jcohy,jiac，jiachao23，study，source
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: jcohy
organization:
organization_url:
github_username: jiachao23
location: ShannXi, China
email: jia_chao23@126.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档

  -
    href: /open-source/
    label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于
  -
    href: /resource/
    label: 资源
# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: jiachao23/jiachao23.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: jiachao23
    repo: blog-comments
    oauth:
        client_id: 927f8f186d0df5eb5dd5
        client_secret: ec70cb3bda660edaf4ca53626b0d671e8eca352b
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: jiachao23
    repo: blog-comments
    clientID: 927f8f186d0df5eb5dd5
    clientSecret: ec70cb3bda660edaf4ca53626b0d671e8eca352b
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
#    analytics_id: UA-80669434-1
